language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

script:
  ./bootstrap.sh

before_install:
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get update -qq && sudo apt-get install -y libssl-dev libsasl2-dev
  - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update && brew install openssl